apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-shopmates-web
  namespace: devops-nhattien
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/kubernetes/volume/shopmates
    server: 192.168.49.1
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shopmates-web
  namespace: devops-nhattien
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-shopmates-web
  storageClassName: ""
  selector:
    matchLabels:
      environment: dev