apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-shopmates-admin
  namespace: devops-nhattien
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /home/axyres/kubernetes/volume/shopmates
    server: 192.168.49.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-shopmates-admin
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-shopmates-admin
  selector:
    matchLabels:
      environment: dev