apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-quangcar-api
  namespace: devops-nhattien
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  storageClassName: ""
  nfs:
    path: /var/kubernetes/volume/quangcar
    server: 192.168.49.1
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-quangcar-api
  namespace: devops-nhattien
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-quangcar-api
  storageClassName: ""
  selector:
    matchLabels:
      environment: dev